/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/user/index'
import { Route as AuthenticatedTrafficResetIndexRouteImport } from './routes/_authenticated/traffic-reset/index'
import { Route as AuthenticatedTicketIndexRouteImport } from './routes/_authenticated/ticket/index'
import { Route as AuthenticatedThemeIndexRouteImport } from './routes/_authenticated/theme/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPluginIndexRouteImport } from './routes/_authenticated/plugin/index'
import { Route as AuthenticatedPlanIndexRouteImport } from './routes/_authenticated/plan/index'
import { Route as AuthenticatedPaymentIndexRouteImport } from './routes/_authenticated/payment/index'
import { Route as AuthenticatedOrderIndexRouteImport } from './routes/_authenticated/order/index'
import { Route as AuthenticatedNoticeIndexRouteImport } from './routes/_authenticated/notice/index'
import { Route as AuthenticatedMailTemplateIndexRouteImport } from './routes/_authenticated/mail-template/index'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGiftCardIndexRouteImport } from './routes/_authenticated/gift-card/index'
import { Route as AuthenticatedCouponIndexRouteImport } from './routes/_authenticated/coupon/index'
import { Route as AuthenticatedConfigIndexRouteImport } from './routes/_authenticated/config/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedServerRouteIndexRouteImport } from './routes/_authenticated/server/route/index'
import { Route as AuthenticatedServerManageIndexRouteImport } from './routes/_authenticated/server/manage/index'
import { Route as AuthenticatedServerMachineIndexRouteImport } from './routes/_authenticated/server/machine/index'
import { Route as AuthenticatedServerGroupIndexRouteImport } from './routes/_authenticated/server/group/index'
import { Route as AuthenticatedServerDnsIndexRouteImport } from './routes/_authenticated/server/dns/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrafficResetIndexRoute =
  AuthenticatedTrafficResetIndexRouteImport.update({
    id: '/traffic-reset/',
    path: '/traffic-reset/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketIndexRoute =
  AuthenticatedTicketIndexRouteImport.update({
    id: '/ticket/',
    path: '/ticket/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedThemeIndexRoute = AuthenticatedThemeIndexRouteImport.update({
  id: '/theme/',
  path: '/theme/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPluginIndexRoute =
  AuthenticatedPluginIndexRouteImport.update({
    id: '/plugin/',
    path: '/plugin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanIndexRoute = AuthenticatedPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentIndexRoute =
  AuthenticatedPaymentIndexRouteImport.update({
    id: '/payment/',
    path: '/payment/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderIndexRoute = AuthenticatedOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoticeIndexRoute =
  AuthenticatedNoticeIndexRouteImport.update({
    id: '/notice/',
    path: '/notice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailTemplateIndexRoute =
  AuthenticatedMailTemplateIndexRouteImport.update({
    id: '/mail-template/',
    path: '/mail-template/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGiftCardIndexRoute =
  AuthenticatedGiftCardIndexRouteImport.update({
    id: '/gift-card/',
    path: '/gift-card/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCouponIndexRoute =
  AuthenticatedCouponIndexRouteImport.update({
    id: '/coupon/',
    path: '/coupon/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigIndexRoute =
  AuthenticatedConfigIndexRouteImport.update({
    id: '/config/',
    path: '/config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServerRouteIndexRoute =
  AuthenticatedServerRouteIndexRouteImport.update({
    id: '/server/route/',
    path: '/server/route/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServerManageIndexRoute =
  AuthenticatedServerManageIndexRouteImport.update({
    id: '/server/manage/',
    path: '/server/manage/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServerMachineIndexRoute =
  AuthenticatedServerMachineIndexRouteImport.update({
    id: '/server/machine/',
    path: '/server/machine/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServerGroupIndexRoute =
  AuthenticatedServerGroupIndexRouteImport.update({
    id: '/server/group/',
    path: '/server/group/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServerDnsIndexRoute =
  AuthenticatedServerDnsIndexRouteImport.update({
    id: '/server/dns/',
    path: '/server/dns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/config/': typeof AuthenticatedConfigIndexRoute
  '/coupon/': typeof AuthenticatedCouponIndexRoute
  '/gift-card/': typeof AuthenticatedGiftCardIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/mail-template/': typeof AuthenticatedMailTemplateIndexRoute
  '/notice/': typeof AuthenticatedNoticeIndexRoute
  '/order/': typeof AuthenticatedOrderIndexRoute
  '/payment/': typeof AuthenticatedPaymentIndexRoute
  '/plan/': typeof AuthenticatedPlanIndexRoute
  '/plugin/': typeof AuthenticatedPluginIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/system/': typeof AuthenticatedSystemIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/theme/': typeof AuthenticatedThemeIndexRoute
  '/ticket/': typeof AuthenticatedTicketIndexRoute
  '/traffic-reset/': typeof AuthenticatedTrafficResetIndexRoute
  '/user/': typeof AuthenticatedUserIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/server/dns/': typeof AuthenticatedServerDnsIndexRoute
  '/server/group/': typeof AuthenticatedServerGroupIndexRoute
  '/server/machine/': typeof AuthenticatedServerMachineIndexRoute
  '/server/manage/': typeof AuthenticatedServerManageIndexRoute
  '/server/route/': typeof AuthenticatedServerRouteIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/config': typeof AuthenticatedConfigIndexRoute
  '/coupon': typeof AuthenticatedCouponIndexRoute
  '/gift-card': typeof AuthenticatedGiftCardIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/mail-template': typeof AuthenticatedMailTemplateIndexRoute
  '/notice': typeof AuthenticatedNoticeIndexRoute
  '/order': typeof AuthenticatedOrderIndexRoute
  '/payment': typeof AuthenticatedPaymentIndexRoute
  '/plan': typeof AuthenticatedPlanIndexRoute
  '/plugin': typeof AuthenticatedPluginIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/theme': typeof AuthenticatedThemeIndexRoute
  '/ticket': typeof AuthenticatedTicketIndexRoute
  '/traffic-reset': typeof AuthenticatedTrafficResetIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/server/dns': typeof AuthenticatedServerDnsIndexRoute
  '/server/group': typeof AuthenticatedServerGroupIndexRoute
  '/server/machine': typeof AuthenticatedServerMachineIndexRoute
  '/server/manage': typeof AuthenticatedServerManageIndexRoute
  '/server/route': typeof AuthenticatedServerRouteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/config/': typeof AuthenticatedConfigIndexRoute
  '/_authenticated/coupon/': typeof AuthenticatedCouponIndexRoute
  '/_authenticated/gift-card/': typeof AuthenticatedGiftCardIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/mail-template/': typeof AuthenticatedMailTemplateIndexRoute
  '/_authenticated/notice/': typeof AuthenticatedNoticeIndexRoute
  '/_authenticated/order/': typeof AuthenticatedOrderIndexRoute
  '/_authenticated/payment/': typeof AuthenticatedPaymentIndexRoute
  '/_authenticated/plan/': typeof AuthenticatedPlanIndexRoute
  '/_authenticated/plugin/': typeof AuthenticatedPluginIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/theme/': typeof AuthenticatedThemeIndexRoute
  '/_authenticated/ticket/': typeof AuthenticatedTicketIndexRoute
  '/_authenticated/traffic-reset/': typeof AuthenticatedTrafficResetIndexRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/server/dns/': typeof AuthenticatedServerDnsIndexRoute
  '/_authenticated/server/group/': typeof AuthenticatedServerGroupIndexRoute
  '/_authenticated/server/machine/': typeof AuthenticatedServerMachineIndexRoute
  '/_authenticated/server/manage/': typeof AuthenticatedServerManageIndexRoute
  '/_authenticated/server/route/': typeof AuthenticatedServerRouteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/chats/'
    | '/config/'
    | '/coupon/'
    | '/gift-card/'
    | '/help-center/'
    | '/knowledge/'
    | '/mail-template/'
    | '/notice/'
    | '/order/'
    | '/payment/'
    | '/plan/'
    | '/plugin/'
    | '/settings/'
    | '/system/'
    | '/tasks/'
    | '/theme/'
    | '/ticket/'
    | '/traffic-reset/'
    | '/user/'
    | '/users/'
    | '/server/dns/'
    | '/server/group/'
    | '/server/machine/'
    | '/server/manage/'
    | '/server/route/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/config'
    | '/coupon'
    | '/gift-card'
    | '/help-center'
    | '/knowledge'
    | '/mail-template'
    | '/notice'
    | '/order'
    | '/payment'
    | '/plan'
    | '/plugin'
    | '/settings'
    | '/system'
    | '/tasks'
    | '/theme'
    | '/ticket'
    | '/traffic-reset'
    | '/user'
    | '/users'
    | '/server/dns'
    | '/server/group'
    | '/server/machine'
    | '/server/manage'
    | '/server/route'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/config/'
    | '/_authenticated/coupon/'
    | '/_authenticated/gift-card/'
    | '/_authenticated/help-center/'
    | '/_authenticated/knowledge/'
    | '/_authenticated/mail-template/'
    | '/_authenticated/notice/'
    | '/_authenticated/order/'
    | '/_authenticated/payment/'
    | '/_authenticated/plan/'
    | '/_authenticated/plugin/'
    | '/_authenticated/settings/'
    | '/_authenticated/system/'
    | '/_authenticated/tasks/'
    | '/_authenticated/theme/'
    | '/_authenticated/ticket/'
    | '/_authenticated/traffic-reset/'
    | '/_authenticated/user/'
    | '/_authenticated/users/'
    | '/_authenticated/server/dns/'
    | '/_authenticated/server/group/'
    | '/_authenticated/server/machine/'
    | '/_authenticated/server/manage/'
    | '/_authenticated/server/route/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traffic-reset/': {
      id: '/_authenticated/traffic-reset/'
      path: '/traffic-reset'
      fullPath: '/traffic-reset/'
      preLoaderRoute: typeof AuthenticatedTrafficResetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ticket/': {
      id: '/_authenticated/ticket/'
      path: '/ticket'
      fullPath: '/ticket/'
      preLoaderRoute: typeof AuthenticatedTicketIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/theme/': {
      id: '/_authenticated/theme/'
      path: '/theme'
      fullPath: '/theme/'
      preLoaderRoute: typeof AuthenticatedThemeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/plugin/': {
      id: '/_authenticated/plugin/'
      path: '/plugin'
      fullPath: '/plugin/'
      preLoaderRoute: typeof AuthenticatedPluginIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/': {
      id: '/_authenticated/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof AuthenticatedPlanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/': {
      id: '/_authenticated/payment/'
      path: '/payment'
      fullPath: '/payment/'
      preLoaderRoute: typeof AuthenticatedPaymentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order/': {
      id: '/_authenticated/order/'
      path: '/order'
      fullPath: '/order/'
      preLoaderRoute: typeof AuthenticatedOrderIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notice/': {
      id: '/_authenticated/notice/'
      path: '/notice'
      fullPath: '/notice/'
      preLoaderRoute: typeof AuthenticatedNoticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail-template/': {
      id: '/_authenticated/mail-template/'
      path: '/mail-template'
      fullPath: '/mail-template/'
      preLoaderRoute: typeof AuthenticatedMailTemplateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gift-card/': {
      id: '/_authenticated/gift-card/'
      path: '/gift-card'
      fullPath: '/gift-card/'
      preLoaderRoute: typeof AuthenticatedGiftCardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupon/': {
      id: '/_authenticated/coupon/'
      path: '/coupon'
      fullPath: '/coupon/'
      preLoaderRoute: typeof AuthenticatedCouponIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config/': {
      id: '/_authenticated/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof AuthenticatedConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/server/route/': {
      id: '/_authenticated/server/route/'
      path: '/server/route'
      fullPath: '/server/route/'
      preLoaderRoute: typeof AuthenticatedServerRouteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/server/manage/': {
      id: '/_authenticated/server/manage/'
      path: '/server/manage'
      fullPath: '/server/manage/'
      preLoaderRoute: typeof AuthenticatedServerManageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/server/machine/': {
      id: '/_authenticated/server/machine/'
      path: '/server/machine'
      fullPath: '/server/machine/'
      preLoaderRoute: typeof AuthenticatedServerMachineIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/server/group/': {
      id: '/_authenticated/server/group/'
      path: '/server/group'
      fullPath: '/server/group/'
      preLoaderRoute: typeof AuthenticatedServerGroupIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/server/dns/': {
      id: '/_authenticated/server/dns/'
      path: '/server/dns'
      fullPath: '/server/dns/'
      preLoaderRoute: typeof AuthenticatedServerDnsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedConfigIndexRoute: typeof AuthenticatedConfigIndexRoute
  AuthenticatedCouponIndexRoute: typeof AuthenticatedCouponIndexRoute
  AuthenticatedGiftCardIndexRoute: typeof AuthenticatedGiftCardIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
  AuthenticatedMailTemplateIndexRoute: typeof AuthenticatedMailTemplateIndexRoute
  AuthenticatedNoticeIndexRoute: typeof AuthenticatedNoticeIndexRoute
  AuthenticatedOrderIndexRoute: typeof AuthenticatedOrderIndexRoute
  AuthenticatedPaymentIndexRoute: typeof AuthenticatedPaymentIndexRoute
  AuthenticatedPlanIndexRoute: typeof AuthenticatedPlanIndexRoute
  AuthenticatedPluginIndexRoute: typeof AuthenticatedPluginIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedThemeIndexRoute: typeof AuthenticatedThemeIndexRoute
  AuthenticatedTicketIndexRoute: typeof AuthenticatedTicketIndexRoute
  AuthenticatedTrafficResetIndexRoute: typeof AuthenticatedTrafficResetIndexRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedServerDnsIndexRoute: typeof AuthenticatedServerDnsIndexRoute
  AuthenticatedServerGroupIndexRoute: typeof AuthenticatedServerGroupIndexRoute
  AuthenticatedServerMachineIndexRoute: typeof AuthenticatedServerMachineIndexRoute
  AuthenticatedServerManageIndexRoute: typeof AuthenticatedServerManageIndexRoute
  AuthenticatedServerRouteIndexRoute: typeof AuthenticatedServerRouteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedConfigIndexRoute: AuthenticatedConfigIndexRoute,
  AuthenticatedCouponIndexRoute: AuthenticatedCouponIndexRoute,
  AuthenticatedGiftCardIndexRoute: AuthenticatedGiftCardIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  AuthenticatedMailTemplateIndexRoute: AuthenticatedMailTemplateIndexRoute,
  AuthenticatedNoticeIndexRoute: AuthenticatedNoticeIndexRoute,
  AuthenticatedOrderIndexRoute: AuthenticatedOrderIndexRoute,
  AuthenticatedPaymentIndexRoute: AuthenticatedPaymentIndexRoute,
  AuthenticatedPlanIndexRoute: AuthenticatedPlanIndexRoute,
  AuthenticatedPluginIndexRoute: AuthenticatedPluginIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedThemeIndexRoute: AuthenticatedThemeIndexRoute,
  AuthenticatedTicketIndexRoute: AuthenticatedTicketIndexRoute,
  AuthenticatedTrafficResetIndexRoute: AuthenticatedTrafficResetIndexRoute,
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedServerDnsIndexRoute: AuthenticatedServerDnsIndexRoute,
  AuthenticatedServerGroupIndexRoute: AuthenticatedServerGroupIndexRoute,
  AuthenticatedServerMachineIndexRoute: AuthenticatedServerMachineIndexRoute,
  AuthenticatedServerManageIndexRoute: AuthenticatedServerManageIndexRoute,
  AuthenticatedServerRouteIndexRoute: AuthenticatedServerRouteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
